# Output-Full Analysis

The function of this notebook serves to run some analysis on the results that we have find after retriving from the website.

In [25]:
# Display all the inputs

import pandas as pd

In [27]:
df = pd.read_csv("./output-full/posts.csv")
df.head()

   thread_id                             thread_title  \
0      59646  早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。
1      59646  早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。
2      59646  早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。
3      59646  早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。
4      59646  早期小肝癌-骨转肺转脑转-晚期，经消融介入手术放疗、靶免等综合治疗，完全缓解。

                                        thread_url  post_id  is_opening_post  \
0  http://www.yuaigongwu.com/thread-59646-1-1.html   778403             True
1  http://www.yuaigongwu.com/thread-59646-1-1.html   778497            False
2  http://www.yuaigongwu.com/thread-59646-1-1.html   778498            False
3  http://www.yuaigongwu.com/thread-59646-1-1.html   778510            False
4  http://www.yuaigongwu.com/thread-59646-1-1.html   778591            False

  floor         author           posted_at  \
0    楼主        hwy1368  2018-8-19 11:10:40
1    沙发           chjw  2018-8-19 16:25:43
2    板凳           chjw  2018-8-19 16:26:10
3    地板  best500728060  2018-8-19 17:23:08
4   5 #        hwy1368  2018-8-19 21:53:20


In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8604 entries, 0 to 8603
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   thread_id        8604 non-null   int64
 1   thread_title     8604 non-null   str
 2   thread_url       8604 non-null   str
 3   post_id          8604 non-null   int64
 4   is_opening_post  8604 non-null   bool
 5   floor            8604 non-null   str
 6   author           8604 non-null   str
 7   posted_at        8604 non-null   str
 8   content          8604 non-null   str
 9   image_urls       8604 non-null   str
 10  link_urls        8604 non-null   str
 11  thread_page      8604 non-null   int64
 12  source_url       8604 non-null   str
dtypes: bool(1), int64(3), str(9)
memory usage: 815.2 KB

In [24]:
with pd.option_context('display.max_colwidth', None):
    display(df.loc[df["thread_id"] == 59646, ["thread_url", "source_url"]])

,thread_url,source_url
0,http://www.yuaigongwu.com/thread-59646-1-1.html,http://www.yuaigongwu.com/thread-59646-1-1.html
1,http://www.yuaigongwu.com/thread-59646-1-1.html,http://www.yuaigongwu.com/thread-59646-1-1.html
2,http://www.yuaigongwu.com/thread-59646-1-1.html,http://www.yuaigongwu.com/thread-59646-1-1.html
3,http://www.yuaigongwu.com/thread-59646-1-1.html,http://www.yuaigongwu.com/thread-59646-1-1.html
4,http://www.yuaigongwu.com/thread-59646-1-1.html,http://www.yuaigongwu.com/thread-59646-1-1.html
...,...,...
899,http://www.yuaigongwu.com/thread-59646-1-1.html,http://www.yuaigongwu.com/forum.php?mod=viewthread&tid=59646&extra=page%3D1&page=91
900,http://www.yuaigongwu.com/thread-59646-1-1.html,http://www.yuaigongwu.com/forum.php?mod=viewthread&tid=59646&extra=page%3D1&page=91
901,http://www.yuaigongwu.com/thread-59646-1-1.html,http://www.yuaigongwu.com/forum.php?mod=viewthread&tid=59646&extra=page%3D1&page=91
902,http://www.yuaigongwu.com/thread-59646-1-1.html,http://www.yuaigongwu.com/forum.php?mod=viewthread&tid=59646&extra=page%3D1&page=91
903,http://www.yuaigongwu.com/thread-59646-1-1.html,http://www.yuaigongwu.com/forum.php?mod=viewthread&tid=59646&extra=page%3D1&page=91